### ISSUE TITLE
Ampliación de los datos historicos dolar BOLSA/MEP

### ISSUE THREAD

**Issue by vSchiaffino** [enzonotario/esjs-argentina-datos-api#1]
Buenas! Paso una página que contiene información histórica del dolar MEP, yo consulte hasta en el 2020 y incluso en esa fecha está la información, por si sirve para ampliar las fechas que ofrece la api

[Aca esta el link](https://www.ambito.com/contenidos/dolar-mep-historico.html)

![image](https://github.com/enzonotario/esjs-argentina-datos-api/assets/49006052/5ffe8317-aed0-4c60-b93c-5eba04eb4685)
 

abajo muestra el precio de referencia, no veo que tenga precio compra/venta eso es lo unico malo

**Comment by enzonotario** [comment]
Hola @vSchiaffino , ya pude ampliar la base de datos de los diferentes dólares. Para el caso del Dólar MEP, encontré datos hasta el 29/10/2018.

Cualquier cosa puedes comentar aquí o abrir otro issue.

Saludos!
