### ISSUE TITLE
Error en tasa banco comafi

### ISSUE THREAD

**Issue by ferminrp** [enzonotario/esjs-argentina-datos-api#3]
El api esta devolviendo tna null cuando en la pagina es 73,5

  {
    "entidad": "BANCO COMAFI SOCIEDAD ANONIMA",
    "logo": "https://www.bcra.gob.ar/Imagenes/logosbancos1/00299.jpg",
    "tnaClientes": null,
    "tnaNoClientes": null,
    "enlace": "https://plazofijodigital.comafi.com.ar/#/simulator/form"
  },

**Comment by enzonotario** [comment]
Corregido @ferminrp , gracias por reportarlo!
