### ISSUE TITLE
Listar Aplicación

### ISSUE THREAD

**Issue by rvalla** [enzonotario/esjs-argentina-datos-api#4]
# Agregar Aplicación a la lista de aplicaciones que consumen ArgentinaDatos.com

## Información de la Aplicación

- **Nombre de la Aplicación:**
 MERC's Harvey Bot

- **URL de la Aplicación:**
 https://t.me/mercsharvey_bot

- **Descripción de la Aplicación:**
  Bot de Telegram para consultar datos del mercado de valores en Argentina.

**Comment by enzonotario** [comment]
Hola @rvalla , listo, Bot sumado!

Exitos!
