### ISSUE TITLE
Consultar historial de cripto

### ISSUE THREAD

**Issue by santivanic** [enzonotario/esjs-argentina-datos-api#5]
Hola! gracias por compartir esta API, es genial!
hay manera de obtener el historial de la cotización cripto?
veo que no existe ese tipo de "casa" pero en los graficos de ejemplo en la docu si que se puede elejir

![image](https://github.com/enzonotario/esjs-argentina-datos-api/assets/60943742/b14962d2-cd00-41ad-90c4-65fede7feada)

**Comment by enzonotario** [comment]
Hola @santivanic , gracias por informarlo!

Si está disponible el endpoint para `cripto`: https://api.argentinadatos.com/v1/cotizaciones/dolares/cripto/ (y también acabo de agregarlo en el Select que mencionas).

Aunque sólo tenemos datos desde el 07/02/2023. Si conoces alguna fuente de datos confiable que contenga los datos anteriores podría agregarlo.

Saludos!
