### ISSUE TITLE
API NaranjaX

### ISSUE THREAD

**Issue by vagrantvaquita** [enzonotario/esjs-argentina-datos-api#6]
No un issue, solo una consulta: Es la api de naranjaX publica? o NaranjaX la creo especialmente para este proyecto?

**Comment by enzonotario** [comment]
No es pública; al igual que el de otras fuentes, han sido creados especialmente para este proyecto, vía comparatasas.ar.

Sin embargo los datos están disponibles tal cual se proveen, sin transformaciones.

Saludos!
