### ISSUE TITLE
[Docs] Añadir CCL como valor válido para `casa` en GET Dólar por casa y fecha

### ISSUE THREAD

**Issue by facupalavecino** [enzonotario/esjs-argentina-datos-api#7]
Hola!

La documentación del endpoint [GET Dólar por casa y fecha](https://argentinadatos.com/docs/operations/get-cotizaciones-dolares-casa-fecha.html) no menciona `contadoconliqui` como un valor válido para `casa`, aunque si lo es. Adjunto fotos de los docs y del endpoint aceptando el valor.

<details><summary>Foto de los docs</summary>

<img width="1091" alt="image" src="https://github.com/user-attachments/assets/62e1efe3-ec78-4a22-a716-570910472dbc">

</details> 

<details><summary>Endpoint acepta el valor</summary>

<img width="833" alt="image" src="https://github.com/user-attachments/assets/0634a0ba-a4b4-4e17-a5fd-f3571d24a2b7">

</details> 

Muy buena API, gracias!

**Comment by enzonotario** [comment]
Genial @facupalavecino , ahí quedó corregida la documentación.

Gracias por reportarlo. Saludos!
