### ISSUE TITLE
Dolar Venta Mayorista en 1

### ISSUE THREAD

**Issue by demacomsistemas** [enzonotario/esjs-argentina-datos-api#8]
Hola Enzo, espero que andes bien.

Veo que la API está devolviendo precio de venta 1 para el dólar mayorista a partir del día 23/10/2024. ¿Por qué puede ser?

  {
    "casa": "mayorista",
    "compra": 962.57,
    "venta": 1,
    "fecha": "2024-10-23"
  },
  {
    "casa": "mayorista",
    "compra": 962.57,
    "venta": 1,
    "fecha": "2024-10-24"
  },
  {
    "casa": "mayorista",
    "compra": 962.57,
    "venta": 1,
    "fecha": "2024-10-25"
  }

Saludos
Damian.

**Comment by enzonotario** [comment]
Buenas @demacomsistemas, esto es debido a que la Fuente de Datos (https://dolarhoy.com/) está devolviendo ese valor desde dicha fecha, por lo tanto el error se propagó hacia DolarApi y hacia ArgentinaDatos.

Igualmente estos días lo corrijo aquí, y cambio la Fuente de Datos en DolarApi.

Gracias por reportarlo, aviso por aquí cuando esté corregido. Saludos!

**Comment by enzonotario** [comment]
Buenas @demacomsistemas , ya quedó corregido. Gracias nuevamente. Saludos!
